### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by midhatdrops** [Carolis/typescript4noobs#14]
Gostaria de desenvolver se possível uma explicação sobre o uso dos generics em Typescript . Teria algum problema ? Assim que tiver pronto realizo o PR :)

**Comment by Carolis** [comment]
@midhatdrops ficarei muito feliz com a contribuição!!! Fica a vontade =) 
Se precisar de mais alguma coisa é só falar também <3

**Comment by midhatdrops** [comment]
PR adicionado! [PR#1](https://github.com/Carolis/typescript4noobs/pull/15)

**Comment by Carolis** [comment]
ficou muito top maninho, valeu pela contribuição, se quiser pode mandar um PR pra add teu nome nas contribuições tbm!!

**Comment by midhatdrops** [comment]
Adicionei eu e outros colaboradores que deram PR e estavam listados :)
[PR#16](https://github.com/Carolis/typescript4noobs/pull/16)
